age:
    keyFile: ENC[AES256_GCM,data:6jRoRsacuKucq8n87/WsDM93EBZ2uADs3mQqNY8r1tcHwsSE83e5rBipWXlO4JYo5xrHwyTj5GICncvIhaYJpZe3Xi28qbfS/1sR/p6U3p/Naw+JkUhp3v5D6uaiBJuyS9mmUYSGwpi723jRJ7os6uL6vnc/PEvxg8Ch8tUJl2qRORwbxA5MMZIVpNeYac0H5HGnYSU9rLtA3Mn/aW1cUIh6bW7AQBiSPHe5RQO1CIiRX+PPDVGeW/Q2b9TA,iv:vBUPRHyIVvWWG/JzvlTDLFwiLG522oaXEBav3UVCuNs=,tag:ZYbHJP7zhggOsNe/ngiRKw==,type:str]
sops:
    age:
        - recipient: age1ftcurndrgcxtcqd7p4r0z5mwavrt9ux9slvd3zlxqgzn4vs54vqqg0xk3m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QmV3aDFGODVKQXZKeHBu
            Sjk1T2FJSzMrRjdPWTk3Z2JveVp6Nnl6SGxjClk4cStRQVpzL1JGMnJzOWgzR1VH
            U3dlcis5YUIwVm1valFxZVExemJId1EKLS0tIDhaMFBzdUtYYzQ4a2FlOHhNUEJt
            cVZYeFpJdHJiNFJsYmRvbUZFRDdJYUUK/FBOVYbAnNQXuDHC9V4hjaf9WbDrj7PJ
            9nPaWLIjOWpHIrgleFbjlyqWhsMYGUN2iTotRr/XwGUTq79m2GpLtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T23:19:55Z"
    mac: ENC[AES256_GCM,data:BhpYUvTRNqhvt72MF3HDMqxW3tBe8tPxqdILtgjxpSYt8o7j7V0G6lcSOVeWB/6fgCc523ccT1/GB2fDobtD1hSR8fRES59UVRMQIN/J/KAVrAVOhtpwo/Q7qvpD2jPsNMNLI2hygfQwtPUa8cRBYyEk5FYhOIZvPoYJXqAEFwc=,iv:uYCYvs19rLG1sC5etR6aVqpI6J759fhH2HVqKQvMoX0=,tag:latPzZsrp6XFrhex3qQtsw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
