age:
    keyFile: ENC[AES256_GCM,data:6jRoRsacuKucq8n87/WsDM93EBZ2uADs3mQqNY8r1tcHwsSE83e5rBipWXlO4JYo5xrHwyTj5GICncvIhaYJpZe3Xi28qbfS/1sR/p6U3p/Naw+JkUhp3v5D6uaiBJuyS9mmUYSGwpi723jRJ7os6uL6vnc/PEvxg8Ch8tUJl2qRORwbxA5MMZIVpNeYac0H5HGnYSU9rLtA3Mn/aW1cUIh6bW7AQBiSPHe5RQO1CIiRX+PPDVGeW/Q2b9TA,iv:vBUPRHyIVvWWG/JzvlTDLFwiLG522oaXEBav3UVCuNs=,tag:ZYbHJP7zhggOsNe/ngiRKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QlQwdUNEdzB0alJxUU90
            TUc1eUR1bVEwK2d4Q2NrSEI1aE9PODdZb1ZFCjhVbFljMGsyc1dPSmRCV240SUV4
            aFlHdUdWL1ZHVjJPOVJxNHFONXJocjQKLS0tIFdyREtUM0d6QUJhbzBWbVZ0REcv
            SCtrbDdhL3pHVjhZYXJiSS9BaVhOYzQKqnkZjiSsWlodoIrJlz49IJ1YgBLwCyqg
            5ef/FuGNA/mE4/WoMrtNYC06p5fAj6XrlHRFIomtQcc2eMkjrTFemw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ftcurndrgcxtcqd7p4r0z5mwavrt9ux9slvd3zlxqgzn4vs54vqqg0xk3m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsa0hPRUxxMW9zTWE0SEFh
            c0FwMFFrS0ZaMklOQW5xN0hXK3BnZEhvaWxNCi9RVEpDRWhGS0ZUdTFjb0pGTjBY
            emRRRWUwVjVCb1dPQVNGUU5lTWZyOUEKLS0tIG92TnNURTRLa0RaWVpPUythaTJZ
            dWRqUytNdksvaTVKcUF4SXZHUUdNb00K4e0u8bFXYUx8TQNJARD4PFK+NNFtENQd
            G/6O8XjGmJTZQ1iHvNANTUFeB219PVKmUZFNfvoc6KPpEOMyCOeA7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x6nxamdaqd9428nth4f4p2ltnm4sehwp9msln0l45h4dpkv2pp8shm7x8l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLckNWNysvaGRVenMvQnNx
            RGVMbERzeU8yQ2lOWFpjeTNhbVR4UnNsaTFVCndlV2tQUTF1OG5OTHNaTTgzVmhP
            OUs3U1BuaHI2Sk5BUTk1NkkzSk1GU0EKLS0tIFBtckFnQkg2RXBTc29XSllxMlZI
            dXRNUi92Rm9rTzZSWU51bUJnYjByYW8KOoQb7L02PDCQKf+0HTOFkXrPnF/g0E/w
            +UXWjZeJO8YFy6+AC1FPWZnAb40UioqWNvuGDRGb1oJzXm4Q5Vh+oQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age107n9zpcrw7qzv3fsdwtmjlzkdc23ga6xfh77dk2fh63nmnuypqjq9xyrvw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFamk2QUF0SXlIMzBzSk1Y
            d0daa1luVjVYVXZDSGFDQm9PZkdPTTBCVDFrCkh5S3F3VEtWcEo1Z2tJNkx6REJl
            NVBlMnB6Q2JDK0JQR01OUnhCNUI5TzAKLS0tIGUwN1QxL1NSWGxBdzBFQ1JZbUJo
            NnU2aUJ0RTRMS20vcU1ORFhYY2szYlEKHG0DUipjMKH5FY0mBr0waeJ3bK0ESIVz
            1j/dXIxrkLKc9NpgaD0SfDhGA72LvNLimZA63fWIjhlvcnaNbcCVfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t4f2nej3l3nzm2m62hmwdmprymgm3ychhmkp7qnd8lk4du95xvgqlhj06j
    lastmodified: "2026-05-04T23:19:55Z"
    mac: ENC[AES256_GCM,data:BhpYUvTRNqhvt72MF3HDMqxW3tBe8tPxqdILtgjxpSYt8o7j7V0G6lcSOVeWB/6fgCc523ccT1/GB2fDobtD1hSR8fRES59UVRMQIN/J/KAVrAVOhtpwo/Q7qvpD2jPsNMNLI2hygfQwtPUa8cRBYyEk5FYhOIZvPoYJXqAEFwc=,iv:uYCYvs19rLG1sC5etR6aVqpI6J759fhH2HVqKQvMoX0=,tag:latPzZsrp6XFrhex3qQtsw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
