keys:
  - &thinkbook_ssh_host_key age1ftcurndrgcxtcqd7p4r0z5mwavrt9ux9slvd3zlxqgzn4vs54vqqg0xk3m

creation_rules:
  - path_regex: ^[^\.].+\.yaml$
    key_groups:
    - age:
      - *thinkbook_ssh_host_key
