keys:
  - &thinkbook_ssh_host_key age1ftcurndrgcxtcqd7p4r0z5mwavrt9ux9slvd3zlxqgzn4vs54vqqg0xk3m
  - &wsl_thinkbook_ssh_host_key age1x6nxamdaqd9428nth4f4p2ltnm4sehwp9msln0l45h4dpkv2pp8shm7x8l
  - &wsl_matebook_ssh_host_key age107n9zpcrw7qzv3fsdwtmjlzkdc23ga6xfh77dk2fh63nmnuypqjq9xyrvw

creation_rules:
  - path_regex: ^[^\.].+\.yaml$
    key_groups:
    - age:
      - *thinkbook_ssh_host_key
      - *wsl_thinkbook_ssh_host_key
      - *wsl_matebook_ssh_host_key
