age:
    keyFile: ENC[AES256_GCM,data:6jRoRsacuKucq8n87/WsDM93EBZ2uADs3mQqNY8r1tcHwsSE83e5rBipWXlO4JYo5xrHwyTj5GICncvIhaYJpZe3Xi28qbfS/1sR/p6U3p/Naw+JkUhp3v5D6uaiBJuyS9mmUYSGwpi723jRJ7os6uL6vnc/PEvxg8Ch8tUJl2qRORwbxA5MMZIVpNeYac0H5HGnYSU9rLtA3Mn/aW1cUIh6bW7AQBiSPHe5RQO1CIiRX+PPDVGeW/Q2b9TA,iv:vBUPRHyIVvWWG/JzvlTDLFwiLG522oaXEBav3UVCuNs=,tag:ZYbHJP7zhggOsNe/ngiRKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2alZzMmlsQ0lIOEo0VTZj
            aEhlSlh4bWQrUUN2eGtmczVYelhMK1cwUWtRCjJLQ0lJMGRUeC8xTVFVOTErUnpI
            dU12eFV2MUlBTUxRZUIvUURwY0x2N0UKLS0tIDNHVWdpZTIrMThNdjdVcTdEVEtR
            MzVMT3gvYTRKa0sxQ3l3UHVxck81akkKrzXCwWI+uK93+ZZ/W1JZ1zZNGGuj9jeF
            lyKk3DkSARD83JDzvIu1gAgVEfO9e8TqP09UwsacySThHwwjCSgRWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ftcurndrgcxtcqd7p4r0z5mwavrt9ux9slvd3zlxqgzn4vs54vqqg0xk3m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMWhBWlpxR2tKQjlDMm9m
            dTg2UGFlRng3UUk0Um9tQ1RxRWVOUWNHTEhBCkJvWElsK2R3NnpsUEQ3L2R3c2xx
            ZGNGYlJXWENUV0EwWFhzUmZMUjc5eEUKLS0tIGJzUVR6QTV1VGpsUEg2bTBieHBM
            MHBLYmpvSEc1VWI5ekl4TFM4dHlMUE0KWW/+n/5qJV57rmrf7UJyJjVQRbfQzsGp
            5BpI4PiHcjD/mdYrn1X+cQwIR2mbN995fh+fthhIla8M2zs3GaGUow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x6nxamdaqd9428nth4f4p2ltnm4sehwp9msln0l45h4dpkv2pp8shm7x8l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WWtoV0N4SVNSUTBwRk5w
            WENoa1FzNWZ2Y3NBT3FpN1BUeU5YRkxkZW5rCndRaWRtdDFXV3pxVUk4Y1FSdzVD
            elE0bHBsNkZaOXI5YTAyWkVUdHlKWmsKLS0tIE82TUZ1QzlOUUQ2dUh1bDk2YXdQ
            ZStxZjRQckxyQ2o3QUdvRm9jOWlFdlkKsisncwv+Xe4UXJ34BvMcWRc0i7BkzABp
            0deUDZpiplGK5bpCbUn9IqxdzuWekbnTzyJCUDQaPeywSiEQyBvGPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age107n9zpcrw7qzv3fsdwtmjlzkdc23ga6xfh77dk2fh63nmnuypqjq9xyrvw
    lastmodified: "2026-05-04T23:19:55Z"
    mac: ENC[AES256_GCM,data:BhpYUvTRNqhvt72MF3HDMqxW3tBe8tPxqdILtgjxpSYt8o7j7V0G6lcSOVeWB/6fgCc523ccT1/GB2fDobtD1hSR8fRES59UVRMQIN/J/KAVrAVOhtpwo/Q7qvpD2jPsNMNLI2hygfQwtPUa8cRBYyEk5FYhOIZvPoYJXqAEFwc=,iv:uYCYvs19rLG1sC5etR6aVqpI6J759fhH2HVqKQvMoX0=,tag:latPzZsrp6XFrhex3qQtsw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
