age:
    keyFile: ENC[AES256_GCM,data:6jRoRsacuKucq8n87/WsDM93EBZ2uADs3mQqNY8r1tcHwsSE83e5rBipWXlO4JYo5xrHwyTj5GICncvIhaYJpZe3Xi28qbfS/1sR/p6U3p/Naw+JkUhp3v5D6uaiBJuyS9mmUYSGwpi723jRJ7os6uL6vnc/PEvxg8Ch8tUJl2qRORwbxA5MMZIVpNeYac0H5HGnYSU9rLtA3Mn/aW1cUIh6bW7AQBiSPHe5RQO1CIiRX+PPDVGeW/Q2b9TA,iv:vBUPRHyIVvWWG/JzvlTDLFwiLG522oaXEBav3UVCuNs=,tag:ZYbHJP7zhggOsNe/ngiRKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbnFHSldEaVFjeUFLL2VB
            LzdGYU03OW1aVWZVNjgyUFNHaFoyM1VpcUZJCm5vV2tNZkIxM1VuRnB6QjVqNlo2
            bit6TFJFQXlnT1MrNFdMYWpIN2ZnOUkKLS0tIFlMVEduZTBTN041UXFDME9kRXJk
            cEJWM09VeWlGa2k2dHpvK1c4dGI0aG8KOPYk+SuWDWDLE5FjRBoCuSVAlTg9M5Zq
            TKqx7ydjIJ5iSODGYLGau0sROHz9TpCpYhW+qs+pC5QZVlb5MxbZ/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ftcurndrgcxtcqd7p4r0z5mwavrt9ux9slvd3zlxqgzn4vs54vqqg0xk3m
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RlNEMWZXWi81RUxvU2Z2
            ZjJJQmdlQ1ROS0N4SlVhVTE0UUtBYXJaNHgwCmJnbmJJa2FXRUtJdDIyN2Zic0Zp
            V0JibGV6UGwxZW1mTWxYWGlGS2ZaaWcKLS0tIDV1L2tYVlluaXhNek5Pejg4eERH
            RWFsSWZwaUZFb0RIcGxOY0JWdEVRR1EK4WkiGKnKrd+ZNM+z3e+cnniyLY1FR9lT
            j90jAEW/VhRjKGfGvZDh0tDRcrwipmXi/94E92DOf241sZ9V974HBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x6nxamdaqd9428nth4f4p2ltnm4sehwp9msln0l45h4dpkv2pp8shm7x8l
    lastmodified: "2026-05-04T23:19:55Z"
    mac: ENC[AES256_GCM,data:BhpYUvTRNqhvt72MF3HDMqxW3tBe8tPxqdILtgjxpSYt8o7j7V0G6lcSOVeWB/6fgCc523ccT1/GB2fDobtD1hSR8fRES59UVRMQIN/J/KAVrAVOhtpwo/Q7qvpD2jPsNMNLI2hygfQwtPUa8cRBYyEk5FYhOIZvPoYJXqAEFwc=,iv:uYCYvs19rLG1sC5etR6aVqpI6J759fhH2HVqKQvMoX0=,tag:latPzZsrp6XFrhex3qQtsw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
