# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... } : let

  cfg = config.modules.hosts.thinkbook;

in {

  imports = [
    (modulesPath + "/hardware/cpu/intel-npu.nix")
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  config = lib.mkIf cfg.enable {

    boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    fileSystems = {
      "/" = {
        enable = true;
        mountPoint = "/";
        device = "/dev/disk/by-uuid/1a6219c7-681d-43ee-944d-9c8e5cda7460";
        fsType = "ext4";
      };
      "/boot" = {
        enable = true;
        mountPoint = "/boot";
        device = "/dev/disk/by-uuid/87B6-19CE";
        fsType = "vfat";
        options = [ "fmask=0022" "dmask=0022" ];
      };
      "/mnt/c" = {
        enable = true;
        mountPoint = "/mnt/c";
        device = "/dev/disk/by-partuuid/12a5524f-6360-11f1-ae85-806e6f6e6963";
        fsType = "ntfs3";
        options = [ "nofail" "x-systemd.device-timeout=2s" ];
      };
    };

    swapDevices = [ ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.npu.enable = true;
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  };

}
